# ==============================================================================
# Script Name: Polycistron Compartment Enrichment Visualization (Rose Plots)
# Description: This script visualizes the enrichment (fold change) of replication 
#              origins or terminations across different genomic compartments 
#              (e.g., Core, Disruptive, GpDR) using rose plots (polar bar charts).
#
# Required Input Files:
#   1. Processed Data File: A tab-separated values file (e.g., 
#      "policistronAnnotation.tsv") generated by the polycistron enrichment 
#      pipeline. Expected columns include 'event', 'compartment', and 'fold_change'.
# ==============================================================================

# STEP 1: Load Dependencies
# Install any missing packages before loading
required_packages <- c("ggplot2", "dplyr", "rio", "scales", "cowplot")
missing_packages <- required_packages[!(required_packages %in% installed.packages()[, "Package"])]

if (length(missing_packages) > 0) {
  install.packages(missing_packages, dependencies = TRUE)
}

# Load all required libraries
invisible(lapply(required_packages, require, character.only = TRUE))

# STEP 2: Environment Configuration
# Set your working directory (uncomment to use)
setwd("~/Documents/DNAscent-Origins/dataAnalisys/CompartmentAnnotation") 

# STEP 3: Import Processed Data
data <- read.table(file = "policistronAnnotation.tsv", header = TRUE)
# print(data) # Uncomment to verify data structure

# STEP 4: Data Transformation
# Round fold_change values to 4 decimal places
# This overwrites the original column with the rounded values
data$fold_change <- round(data$fold_change, digits = 4)

# STEP 5: Filter and Reclassify Data
# Filter data for DNAscent group classifications and rename events
atlas_sm <- data %>%
  dplyr::filter(event %in% c("lessFrequent", "moreFrequent")) %>%
  dplyr::mutate(event = dplyr::case_when(
    event == "lessFrequent" ~ "single origins",
    event == "moreFrequent" ~ "consensus origins",
    TRUE ~ event
  )) %>%
  dplyr::mutate(event = factor(event, levels = c("single origins", "consensus origins")))

# head(atlas_sm) # Uncomment to verify filtered data

# STEP 6: Define Custom Color Palettes
compartment_colors <- c(
  "Core"       = rgb(254, 196, 79, maxColorValue = 255),  # Light Gold (Mild)
  "Disruptive" = rgb(217, 95, 14, maxColorValue = 255),   # Intense Orange
  "GpDR"       = rgb(153, 52, 4, maxColorValue = 255)     # Burnt Orange/Brown (Very Intense)
)

group_colors <- c(
  "single origins"    = rgb(44, 123, 182, maxColorValue = 255),
  "consensus origins" = rgb(215, 25, 28, maxColorValue = 255)
)

# STEP 7: Define Plotting Function (Rose Plots)
create_rose_plot <- function(df_subset, group_name, text_color) {
  
  max_fc <- max(df_subset$fold_change, na.rm = TRUE)
  y_limit <- max_fc * 1.35  # Buffer to prevent overlap with titles
  y_breaks <- seq(0, ceiling(max_fc), by = 1)
  
  ggplot(df_subset, aes(x = compartment, y = fold_change, fill = compartment)) +
    geom_bar(stat = "identity", width = 1, color = "black") +
    coord_polar(start = 0) +
    scale_fill_manual(values = compartment_colors) +
    scale_y_continuous(limits = c(0, y_limit), breaks = y_breaks) +
    # Radial scale numbers
    geom_text(data = data.frame(y = y_breaks), 
              aes(x = 0.5, y = y, label = sprintf("%.1f", y)),
              inherit.aes = FALSE, size = 2, color = "black", vjust = -0.5) +
    theme_minimal() +
    theme(
      axis.title = element_blank(),
      axis.text = element_blank(),
      panel.grid.major = element_line(color = "gray80", linewidth = 0.4), # Updated from 'size' to 'linewidth'
      panel.grid.minor = element_blank(),
      legend.position = "none"
    )
}

# STEP 8: Generate Individual Plots
p1 <- create_rose_plot(subset(atlas_sm, event == "single origins"), 
                       "single origins", group_colors["single origins"])

p2 <- create_rose_plot(subset(atlas_sm, event == "consensus origins"), 
                       "consensus origins", group_colors["consensus origins"])

# STEP 9: Assemble and Save Final Figure
# 9.1 Extract the shared legend for compartments
dummy_for_legend <- ggplot(atlas_sm, aes(x = compartment, y = fold_change, fill = compartment)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(name = "Genome Compartments", values = compartment_colors) +
  theme_minimal() + 
  theme(legend.position = "bottom", 
        legend.title = element_text(face = "bold"),
        legend.text = element_text(size = 10))

shared_legend <- cowplot::get_legend(dummy_for_legend)

# 9.2 Combine the two rose plots and assign facet labels
combined_row <- cowplot::plot_grid(
  p1, p2, 
  ncol = 2, 
  labels = c("I", "II"), # Added labels to match your original comment
  label_size = 16, 
  label_fontface = "bold",
  label_x = 0.05, label_y = 0.95 # Position labels at top-left of each facet
)

# 9.3 Final assembly: Plots on top, legend on bottom
ROSES <- cowplot::plot_grid(combined_row, shared_legend, ncol = 1, rel_heights = c(1, 0.15))

# Display the final plot
print(ROSES)

# Save to PDF
ggsave("Origins-policistronsAnotated.pdf", 
       plot = ROSES, 
       height = 8, 
       width = 13, 
       units = "cm", 
       dpi = 1200)

message("Success: Rose plots combined and saved as Origins-policistronsAnotated.pdf")