# ==============================================================================
# Script Name: OEM Profile and Statistical Analysis at Replication Origins
# Description: This script computes a metaplot-like profile of Origin Efficiency 
#              Metric (OEM) scores centered around DNA replication origins. It 
#              also generates a boxplot to compare the mean scores across regions, 
#              automatically applying the appropriate statistical test (ANOVA or 
#              Kruskal-Wallis) based on data normality and homogeneity.
#
# Required Input Files:
#   1. OEM bedGraph: "OEM.bedgraph" containing genome-wide OEM scores.
#   2. BED Files: Genomic coordinates for regions of interest 
#      (e.g., "control.bed", "origins.bed", "MiniInitiationZones.bed").
# ==============================================================================

# STEP 1: Load Dependencies
# Suppress package startup messages for cleaner output
required_packages <- c("data.table", "ggplot2", "cowplot", "ggpubr", "car", "tools")
bioc_packages <- c("GenomicRanges")

# Function to safely check and install packages
check_install_packages <- function(pkg_list, is_bioc = FALSE) {
  for (pkg in pkg_list) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      if (is_bioc) {
        if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
        BiocManager::install(pkg, update = FALSE, ask = FALSE)
      } else {
        install.packages(pkg)
      }
    }
    suppressPackageStartupMessages(library(pkg, character.only = TRUE))
  }
}

check_install_packages(required_packages)
check_install_packages(bioc_packages, is_bioc = TRUE)

# STEP 2: Environment Configuration & Variables
SUBDIR <- "OEM_Analisys/"
base_dir <- file.path("~/Documents/DNAscent-Origins/dataAnalisys/Profile", SUBDIR)

# Ensure the directory exists before attempting to set the working directory
if (!dir.exists(base_dir)) {
  dir.create(base_dir, recursive = TRUE)
}
setwd(base_dir)

# Input files
bed_files <- c("control.bed", "origins.bed", "MiniInitiationZones.bed")  
bedgraph_file <- "OEM.bedgraph"  

# Analysis parameters
bin_size <- 20          
region_size <- 2000 
nbins <- region_size / bin_size

# Plot labels
plot_title  <- "smAtlas"
Experiment  <- "OEM"

# STEP 3: Load bedGraph Data
message("Loading bedGraph...")
bg <- fread(bedgraph_file, header = FALSE)
setnames(bg, c("chr", "start", "end", "score"))

# Convert to GRanges (using start + 1 for 1-based coordinates)
bg.gr <- GRanges(seqnames = bg$chr, 
                 ranges = IRanges(start = bg$start + 1, end = bg$end), 
                 score = bg$score)

# STEP 4: Define Processing Function
# Function to process each BED file, extract profiles, and calculate raw bin scores
process_bed_file <- function(bed_file, bg.gr, nbins, region_size) {
  message("Processing ", bed_file)
  
  # 1. Load and prepare BED file (assuming at least chr, start, end)
  bed <- fread(bed_file, header = FALSE)
  setnames(bed, 1:3, c("chr", "start", "end")) 
  
  # Convert to GRanges (start + 1 for 1-based indexing)
  gr <- GRanges(seqnames = bed$chr, ranges = IRanges(start = bed$start + 1, end = bed$end))
  
  # Center regions and tile into bins
  gr.centered <- resize(gr, width = region_size, fix = "center")
  gr.bins <- unlist(tile(gr.centered, n = nbins))
  
  # 2. Find overlaps with bedGraph
  ov <- findOverlaps(gr.bins, bg.gr)
  
  # 3. Aggregate scores per bin
  hits_dt <- data.table(
    queryHits = queryHits(ov), 
    subjectHits = subjectHits(ov)
  )
  
  # Calculate bin and region IDs for each hit
  hits_dt[, bin_id := ((queryHits - 1) %% nbins) + 1]
  hits_dt[, region_id := ((queryHits - 1) %/% nbins) + 1]
  hits_dt[, val := bg.gr$score[subjectHits]]
  
  # Calculate mean score for bins that overlap with the bedgraph
  means <- hits_dt[, .(score = mean(val, na.rm = TRUE)), by = .(region_id, bin_id)]
  
  # 4. Create raw data table for all bins (including those with NA/no overlap)
  all_bins_dt <- data.table(
    region_id = rep(1:length(gr), each = nbins),
    bin_id = rep(1:nbins, length(gr))
  )
  
  # Merge calculated means; non-matching bins will have NA score
  bins_dt <- merge(all_bins_dt, means, by = c("region_id", "bin_id"), all.x = TRUE)
  
  # 5. Calculate Metaprofile (mean across all regions for each bin)
  prof <- bins_dt[, .(mean_signal = mean(score, na.rm = TRUE)), by = bin_id]
  
  # 6. Set type/sample label based on filename
  file_type <- tools::file_path_sans_ext(basename(bed_file))
  prof$type <- file_type
  bins_dt$type <- file_type
  
  # Replace NaN generated by mean(empty set) with 0 for robustness
  prof[, mean_signal := fifelse(is.nan(mean_signal), 0, mean_signal)]
  bins_dt[, score := fifelse(is.nan(score), 0, score)]
  
  return(list(profile = prof, raw = bins_dt))
}

# STEP 5: Process All BED Files
all_results <- lapply(bed_files, process_bed_file, bg.gr = bg.gr, nbins = nbins, region_size = region_size)
df <- rbindlist(lapply(all_results, `[[`, "profile"))
df_raw <- rbindlist(lapply(all_results, `[[`, "raw"))

# STEP 6: Rename and Factor Sample Levels
rename_samples <- function(type_name) {
  switch(type_name,
         "control" = "without origins",
         "origins" = "origins",
         "MiniInitiationZones" = "IZD",
         type_name # Default case
  )
}

df[, type := sapply(type, rename_samples)]
df_raw[, type := sapply(type, rename_samples)]

# Define and lock factor levels order
levels_order <- c("without origins", "origins", "IZD")
df$type <- factor(df$type, levels = levels_order)
df_raw$type <- factor(df_raw$type, levels = levels_order)

# STEP 7: Colors and Position Mapping
color_group <- c(
  "without origins" = rgb(0, 0, 255,   maxColorValue = 255),  
  "origins"         = rgb(0, 100, 255, maxColorValue = 255),  
  "IZD"             = rgb(255, 0, 0,   maxColorValue = 255)
)

# Calculate central position for each bin 
positions <- seq(-region_size/2 + bin_size/2, region_size/2 - bin_size/2, by = bin_size)
df$position <- positions[df$bin_id]

# STEP 8: Visualization - Plot A (Metaplot Profile)
pA <- ggplot(df, aes(x = position, y = mean_signal, color = type)) +
  geom_line(linewidth = 1) + 
  geom_vline(xintercept = 0, linetype = "dashed", color = "red", linewidth = 0.5) +
  scale_x_continuous(
    breaks = c(-region_size/2, 0, region_size/2),
    labels = c("start", "center", "end")
  ) +
  scale_color_manual(values = color_group) +
  labs(x = NULL, y = Experiment, color = "Groups") +
  theme_minimal(base_size = 12) +
  theme(
    panel.background = element_rect(color = "black", fill = NA, linewidth = 0.5), 
    axis.ticks = element_line(color = "black", linewidth = 0.2),
    axis.text = element_text(size = 12, color = "black"),
    axis.title.y = element_text(size = 12, color = "black", face = "bold"),
    axis.text.x = element_text(size = 12, color = "black"), 
    plot.title = element_text(hjust = 0.5, face = "bold", size = 12),
    legend.position = "right", 
    legend.text = element_text(size = 12)
  )

print(pA)

# STEP 9: Statistical Analysis (Normality, Homogeneity, ANOVA/Kruskal-Wallis)
# Calculate the mean score per region for the boxplot analysis
region_means <- df_raw[, .(region_mean = mean(score, na.rm = TRUE)), by = .(region_id, type)]

# Safe Shapiro-Wilk (avoids errors when sample size is out of bounds)
safe_shapiro <- function(x) {
  res <- tryCatch({
    if(length(x) >= 3 && length(x) <= 5000) shapiro.test(x)$p.value else NA_real_
  }, error = function(e) {
    message(paste("Shapiro-Wilk error:", e$message))
    NA_real_
  })
  return(as.numeric(res))
}

# Apply normality test by group
shapiro_results <- region_means[, .(shapiro_p = safe_shapiro(region_mean)), by = type]
message("Shapiro-Wilk P-values per group: ", paste(shapiro_results$shapiro_p, collapse = ", "))

# Levene test for homogeneity of variances
levene_result <- leveneTest(region_mean ~ type, data = region_means)
homogeneity <- levene_result$`Pr(>F)`[1] > 0.05
message("Levene Test P-value for homogeneity: ", levene_result$`Pr(>F)`[1])

# Decide which statistical test to use
normality <- all(shapiro_results$shapiro_p > 0.05, na.rm = TRUE)

if(normality && homogeneity) {
  test_used <- "ANOVA"
  aov_res <- aov(region_mean ~ type, data = region_means)
  global_p <- summary(aov_res)[[1]]$`Pr(>F)`[1]
  pairwise_method <- "t.test"
  message("Using Parametric Test: ANOVA and T-tests (Normality and Homogeneity met).")
} else {
  test_used <- "Kruskal-Wallis"
  kruskal_res <- kruskal.test(region_mean ~ type, data = region_means)
  global_p <- kruskal_res$p.value
  pairwise_method <- "wilcox.test"
  message("Using Non-Parametric Test: Kruskal-Wallis and Wilcoxon tests (Normality or Homogeneity failed).")
}
message(paste(test_used, "global P-value:", global_p))

# STEP 10: Visualization - Plot B (Boxplot with Statistics)
comparisons <- list(c("without origins", "origins"), 
                    c("without origins", "IZD"), 
                    c("origins", "IZD"))

pB <- ggplot(region_means, aes(x = type, y = region_mean, fill = type)) +
  geom_boxplot(width = 0.7, outlier.shape = 8, alpha = 0.7) + 
  scale_fill_manual(values = color_group) +
  scale_y_continuous(breaks = seq(-1.8, 1.8, by = 0.2)) +
  coord_cartesian(ylim = c(-1.8, 1.8)) + # Replaced ylim() with coord_cartesian for safer zooming
  labs(x = NULL, y = Experiment, fill = "Groups") +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12),
    axis.title.y = element_text(size = 12, face = "bold"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 12)
  ) + 
  stat_compare_means(method = pairwise_method, 
                     comparisons = comparisons, 
                     label = "p.signif", 
                     tip.length = 0.01,
                     size = 3) 

print(pB)

# STEP 11: Combine and Save Plots
# Combine plots vertically (I and II)
final_plot <- plot_grid(pA, pB, 
                        ncol = 1, 
                        rel_widths = c(1, 1), 
                        labels = c("I", "II"),
                        label_size = 14)

print(final_plot)

# Save the final figures
ggsave("OEM-smAtlas.pdf", final_plot, width = 20, height = 9, units = "cm", dpi = 600)
ggsave("OEM-smAtlas-plotA.pdf", pA, width = 20, height = 4, units = "cm", dpi = 600)
ggsave("OEM-smAtlas-plotB.pdf", pB, width = 20, height = 7, units = "cm", dpi = 600)

message("Success: Script finished. Plots saved to OEM-smAtlas.pdf")