#!/usr/bin/env bash

###################################################################################################
#                                        BCFtoolsMain3                                            #
#                                                                                                 #
#   This script represents the second stage of the SNP analysis pipeline for genomic regions      #
# associated with replication origins, termination zones, chromosomes, and multigene family genes.#
#                                                                                                 #
#   Initially, variant files (VCFs) generated by FreeBayes are filtered using BCFtools and grep,  #
# ensuring that only high-confidence SNPs are retained. These variants are then functionally      #
# annotated with SnpEff, enabling classification based on their genomic context and impact.       #
#                                                                                                 #
#   The distribution of SNPs is analyzed across specific genomic compartments—replication origins,#
# termination regions, multigene family genes, and chromosomes—providing insights into the        #
# mutational dynamics in these domains.                                                           #
#                                                                                                 #
#   Subsequently, the script computes the dN/dS (ω) ratio using a Python script                   #
# (script/calculate_kaks.py), adapted from a previously published approach in the literature.     #
# This method considers the number of synonymous and non-synonymous sites based on aligned and    #
# annotated sequences.                                                                            #
#                                                                                                 #
#   Additionally, a custom C++ program—developed collaboratively by the authors—filters out SNPs  #
# with inconsistent annotations, removing discrepant cases to ensure robustness for evolutionary  #
# analyses.                                                                                       #
#                                                                                                 #
#  Usage:                                                                                         #
#  saveCommand script/BCFtoolsMain3.bash                                                          #
#                                                                                                 #
#                                                                                                 #
#  Copyleft (ɔ) 2025 by Thiago Andrade Franco                                                     #
#                       <thiago.franco@fundacaobutantan.org.br>                                   #
#                                                                                                 #
#  23/04/2025: First version.                                                                     #
###################################################################################################

# Define multigenic families
GENES="DGF-1 GP63 RHS MUC TS MASP HIST"

# SLURM Job
cat > job/BCFtoolsMain3.slurm <<'EOI'
#!/usr/bin/env bash

###################################################################################################
## Module – Calculate the dN/dS ratio to analyze evolutionary pressure on SNPs in specific regions
###################################################################################################
# =====================
# STEP 1: Generate consensus sequences for each sample using BCFtools
# =====================
for SNPS in output/SNPs-sample*-filtered.vcf.gz
do
  bcftools consensus -f input/genome.fasta "${SNPS}" \
  > output/$(basename "${SNPS%-filtered.vcf.gz}")-consensus.fasta
done

# =====================
# STEP 2: Generate multifasta for multigenic families (with and without origin/termination info)
# =====================
for MULTIGENIC in ${GENES}; do

  echo "[INFO] Processing multigenic family: ${MULTIGENIC}"

  # Generate reference FASTA for the entire multigenic family
  bedtools getfasta -fi input/genome.fasta -bed output/${MULTIGENIC}/${MULTIGENIC}.bed -name+ \
  > output/${MULTIGENIC}/${MULTIGENIC}.fasta

  sed -i '/^>/ s/\(::.*\)/_reference/' output/${MULTIGENIC}/${MULTIGENIC}.fasta

  # Generate FASTA for each sample (from consensus)
  for CONSENSUS_FASTA in output/SNPs-sample*-consensus.fasta; do
    BASENAME=$(basename "${CONSENSUS_FASTA}" -consensus.fasta)

    bedtools getfasta -fi "${CONSENSUS_FASTA}" -bed output/${MULTIGENIC}/${MULTIGENIC}.bed -name+ \
    > output/${MULTIGENIC}/${MULTIGENIC}-${BASENAME}.fasta

    sed -i "/^>/ s/\(::.*\)/_${BASENAME}/" output/${MULTIGENIC}/${MULTIGENIC}-${BASENAME}.fasta
  done

  wait

  # Combine reference and all samples for this multigenic family
  cat output/${MULTIGENIC}/${MULTIGENIC}.fasta output/${MULTIGENIC}/${MULTIGENIC}-SNPs-sample*.fasta \
  > output/${MULTIGENIC}/${MULTIGENIC}-multifasta.fasta

  # Now process BEDs for regions with origins/terminations
  for BED_REF in output/${MULTIGENIC}/${MULTIGENIC}-with*.bed; do
    [ -e "$BED_REF" ] || continue
    BED_BASENAME=$(basename "${BED_REF}" .bed)

    echo "[INFO] Processing BED: ${BED_BASENAME}"

    bedtools getfasta -fi input/genome.fasta -bed "${BED_REF}" -name+ \
    > output/${MULTIGENIC}/${BED_BASENAME}-ref.fasta

    sed -i '/^>/ s/\(::.*\)/_reference/' output/${MULTIGENIC}/${BED_BASENAME}-ref.fasta

    for CONSENSUS_FASTA in output/SNPs-sample*-consensus.fasta; do
      BASENAME=$(basename "${CONSENSUS_FASTA}" -consensus.fasta)

      bedtools getfasta -fi "${CONSENSUS_FASTA}" -bed "${BED_REF}" -name+ \
      > output/${MULTIGENIC}/${BED_BASENAME}-${BASENAME}.fasta

      sed -i "/^>/ s/\(::.*\)/_${BASENAME}/" output/${MULTIGENIC}/${BED_BASENAME}-${BASENAME}.fasta
    done

    # Combine reference and samples for this BED
    cat output/${MULTIGENIC}/${BED_BASENAME}-ref.fasta \
        output/${MULTIGENIC}/${BED_BASENAME}-SNPs-sample*.fasta \
    > output/${MULTIGENIC}/${BED_BASENAME}-multifasta.fasta
  done

done

# =====================
# STEP 3: Generate multifasta for origins and termination sites
# =====================
for ORIGINS in output/origins/*.bed; do
  ORIGIN_NAME=$(basename "${ORIGINS%.bed}")

  bedtools getfasta -fi input/genome.fasta -bed "${ORIGINS}" -name+ \
  > output/origins/${ORIGIN_NAME}.fasta

  sed -i '/^>/ s/\(::.*\)/_reference/' output/origins/${ORIGIN_NAME}.fasta

  for CONSENSUS_FASTA in output/SNPs-sample*-consensus.fasta; do
    BASENAME=$(basename "${CONSENSUS_FASTA}" -consensus.fasta)

    bedtools getfasta -fi "${CONSENSUS_FASTA}" -bed "${ORIGINS}" -name+ \
    > output/origins/${ORIGIN_NAME}-${BASENAME}.fasta

    sed -i "/^>/ s/\(::.*\)/_${BASENAME}/" output/origins/${ORIGIN_NAME}-${BASENAME}.fasta
  done

  wait

  # Combine reference and all samples
  cat output/origins/${ORIGIN_NAME}.fasta output/origins/${ORIGIN_NAME}-SNPs-sample*.fasta \
  > output/origins/${ORIGIN_NAME}-multifasta.fasta
done

# =====================
# STEP 4: Generate region-specific TSVs (Per region × sample)
# =====================
mkdir -p output/TSV_ORIGINS
mkdir -p output/TSV_MULTIGENIC

# ================================
# Compress and index annotated VCF files for downstream analysis
# ================================
for VCF in output/SNPs-sample*-annotated.vcf; do
  # Compress the VCF file using bgzip
  bgzip -c "${VCF}" > "${VCF}.gz"

  # Index the compressed VCF file with bcftools
  bcftools index "${VCF}.gz"
done

for VCF in output/SNPs-sample*-annotated.vcf.gz
do
  BASENAME_VCF=$(basename "${VCF}" .vcf.gz)

  # For multigenic regions
  for MULTIGENIC in ${GENES}; do
    for BED in output/${MULTIGENIC}/${MULTIGENIC}*.bed; do
      [ -e "$BED" ] || continue
      BASENAME_BED=$(basename "${BED}" .bed)

      bcftools view -R "${BED}" "${VCF}" | \
      bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO/ANN\n' \
      > output/TSV_MULTIGENIC/${BASENAME_BED}-${BASENAME_VCF}.tsv
    done
  done

  # For origin regions
  for ORIGIN_BED in output/origins/*.bed; do
    [ -e "$ORIGIN_BED" ] || continue
    BASENAME_BED=$(basename "${ORIGIN_BED}" .bed)

    bcftools view -R "${ORIGIN_BED}" "${VCF}" | \
    bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO/ANN\n' \
    > output/TSV_ORIGINS/${BASENAME_BED}-${BASENAME_VCF}.tsv
  done
done

# =====================
# STEP 5: Run Python dN/dS calculator with resource tracking
# =====================
# -------- Origins and Terminations --------
SCRIPT_PATH="script/dndsCalculator.py"
FASTA_GLOB="output/origins/*multifasta.fasta"
TSV_GLOB="output/TSV_ORIGINS/*.tsv"
OUTPUT_FILE="output/dndsRatio-originsAndTerminations.csv"

echo "[INFO] Starting dN/dS calculation for origins and terminations..."

nice -n 19 \
/usr/bin/time --verbose --output=log/dndsCalculator-origins.time \
memusg --output-to-file=log/dndsCalculator-origins.memusg \
python3 "${SCRIPT_PATH}" \
  --fasta_glob "${FASTA_GLOB}" \
  --tsv_glob "${TSV_GLOB}" \
  --output "${OUTPUT_FILE}" \
  1> log/dndsCalculator-origins.out \
  2> log/dndsCalculator-origins.err

if [[ $? -eq 0 ]]; then
  echo "[OK] dN/dS analysis for origins/terminations completed successfully."
else
  echo "[ERROR] Origins/terminations analysis failed. Check log/dndsCalculator-origins.err"
fi


# to Multigenic with and without origins/termination

FASTA_FILES=$(find output/ -type f -name '*-with*multifasta.fasta')

nice -n 19 \
/usr/bin/time --verbose --output=log/dndsCalculator-origins.time \
memusg --output-to-file=log/dndsCalculator-origins.memusg \
python3 script/dndsCalculator2.py \
  --fasta_glob ${FASTA_FILES} \
  --tsv_glob "output/TSV_MULTIGENIC/*-with*-SNPs-sample*-annotated.tsv" \
  --output output/dndsRatio-multigenic.csv
  1> log/dndsCalculator-multigenic.out \
  2> log/dndsCalculator-multigenic.err

if [[ $? -eq 0 ]]; then
  echo "[OK] dN/dS analysis for origins/terminations completed successfully."
else
  echo "[ERROR] Origins/terminations analysis failed. Check log/dndsCalculator-origins.err"
fi

## To multigenic
# Create output directories
mkdir -p output/fasta_MGF
mkdir -p output/TSV_MGF

# Define the gene names
GENES=(DGF-1 GP63 HIST MASP TS RHS MUC)

# Move all corresponding FASTA files
for GENE in "${GENES[@]}"; do
  mv "output/${GENE}/${GENE}-multifasta.fasta" output/fasta_MGF/
done

# Move all corresponding TSV files for each sample 1 to 4
for GENE in "${GENES[@]}"; do
  for SAMPLE in {1..4}; do
    mv "output/TSV_MULTIGENIC/${GENE}-SNPs-sample${SAMPLE}-annotated.tsv" output/TSV_MGF/
  done
done

# Define file globs for FASTA and TSV files
FASTAS_GLOB="output/fasta_MGF/*.fasta"
TSV_GLOB="output/TSV_MGF/*.tsv"

# Run the dN/dS calculator script with resource monitoring
nice -n 19 \
/usr/bin/time --verbose --output=log/dndsCalculator-MGF.time \
memusg --output-to-file=log/dndsCalculator-MGF.memusg \
python3 script/dndsCalculator.py \
  --fasta_glob "$FASTAS_GLOB" \
  --tsv_glob "$TSV_GLOB" \
  --output "output/dndsRatio-MGF.csv" \
  1> log/dndsCalculator-MGF.out \
  2> log/dndsCalculator-MGF.err

###################################################################################################
## STEP 6: Detailed SNP table for ORC regions and flanks (Polycistron-based)
###################################################################################################

# 1. Convert VCF files to simple CHR-POS TSVs for each sample
# This ensures that each sample is counted independently in the Python script
for i in {1..4}; do
    echo "[*] Extracting SNP positions for Sample ${i}..."
    bcftools query -f '%CHROM\t%POS\n' "output/SNPs-sample${i}-filtered.vcf.gz" > "output/snps_sample${i}.tsv"
done

# 2. Define Reference and Input Paths
CHROMSIZES="input/genome-chromoSizes.txt"
POLY_BED="input/polycistrons.bed"    # Only using Polycistrons for strand assignment
BED_DIR="output/origins/"            # Directory containing your ORC sites (.bed files)
OUTPUT_FILE="output/ORC_regions_table_2000bp.tsv"

# 3. Collect the SNP TSV files into a variable
# Order is important: sample1, sample2, sample3, sample4
SNP_FILES="output/snps_sample1.tsv output/snps_sample2.tsv output/snps_sample3.tsv output/snps_sample4.tsv"

# 4. Run the ORC Analyzer Python script
# Arguments:
# 1: Chromosome sizes
# 2: Polycistron reference
# 3: Input directory (BED sites)
# 4: Output TSV file
# 5+: SNP TSV files (one per sample)
echo "[*] Running ORC Analyzer..."

/usr/bin/nice -n 19 \
/usr/bin/time --verbose --output=log/orc_analyzer_poly.time \
python3 script/orc_analyzer.py \
    "${CHROMSIZES}" \
    "${POLY_BED}" \
    "${BED_DIR}" \
    "${OUTPUT_FILE}" \
    ${SNP_FILES} \
1> log/orc_analyzer.out \
2> log/orc_analyzer.err

echo "[*] Analysis complete. Result: ${OUTPUT_FILE}"

EOI

MAIN_JOB_ID=`cat log/sbatch-BCFtoolsMain2.out`

# Submitting the job to Slurm.
  /usr/bin/nice -n 19 /usr/bin/time \
  --verbose \
  --output=log/sbatch-BCFtoolsMain3.time memusg \
  --output-to-file log/sbatch-BCFtoolsMain3.memusg \
    --time --shell "saveCommand sbatch --parsable \
    --dependency=afterany:${MAIN_JOB_ID} \
    --nodes 1 \
  --ntasks ${NUM_OF_CPUS} \
  --mem ${MEMORY_SIZE} \
  -o log/slurm-%A.out \
  -J BCFtoolsMain2 job/BCFtoolsMain3.slurm \
  2> log/sbatch-BCFtoolsMain3.err |
    tee log/sbatch-BCFtoolsMain3.out"

# Check how are going all the running awk processes.
echo "To check the running processes, execute one of the following commands:"
echo "   $> watch -n 1 sequeue"

exit 0
