#!/usr/bin/env bash

###################################################################################################
#                                       BCFtoolsVariables                                         #
#                                                                                                 #
#  Description:                                                                                   #
#  This script contains all the environment variables used in the comprehensive SNP analysis      #
#  pipeline based on variant calls generated by FreeBayes.                                        #
#                                                                                                 #
#  The downstream pipeline utilizes BCFtools, custom Python, and C++ scripts to investigate       #
#  SNP density across different genomic regions, including DNA replication origins/termini,       #
#  multigene families, and specific chromosomes.                                                  #
#                                                                                                 #
#  Furthermore, these variables configure key resources (such as genome annotation files,         #
#  memory, and CPU requirements) for advanced downstream analyses, including:                     #
#    - Functional annotation with SnpEff                                                          #
#    - Evolutionary selection analysis (dN/dS ratios)                                             #
#    - Loss of Heterozygosity (LOH) evaluation                                                    #
#                                                                                                 #
#  Usage:                                                                                         #
#  source script/BCFtoolsVariables.bash  (or  . script/BCFtoolsVariables.bash)                    #
#                                                                                                 #
#  Copyleft (ɔ) 2025 by Thiago Andrade Franco                                                     #
#                       <thiago.franco@fundacaobutantan.org.br>                                   #
#                                                                                                 #
#  23/04/2025: First version.                                                                     #
###################################################################################################

# Number of Memery necessary to slurm
export MEMORY_SIZE="70G"

# Number of CPUS necessary to rum job at slurm
export NUM_OF_CPUS=70

# Genome file that will be used in the annotation gff
export GENOME_GFF="/project/carol/dnascent/project/D-NAscent-Origins/metaData/genome.gff"

# Genome file that will be used in the annotation fasta
export GENOME_FASTA="/project/carol/dnascent/project/D-NAscent-Origins/metaData/genome.fasta"

# Genes analyzed in this pipeline
export GENES="GP63 RHS DGF-1 MASP MUC TS HIST"
