#!/usr/bin/env bash
###################################################################################################
#                                         BCFtoolsPre                                             #
#                                                                                                 #
#  Description:                                                                                   #
#  This script performs the essential pre-processing steps for the downstream SNP analysis        #
#  pipeline, utilizing the variant calls previously generated by FreeBayes.                       #
#                                                                                                 #
#  It establishes the working directory structure and creates symbolic links to the input         #
#  data, ensuring a clean, organized, and reproducible environment for subsequent analyses.       #
#                                                                                                 #
#  This is a foundational step for investigating SNP density near DNA replication origins         #
#  and termini, multigene family variant distribution, as well as downstream steps including      #
#  SnpEff annotation, dN/dS ratio calculations, and Loss of Heterozygosity (LOH) evaluations      #
#  using BCFtools alongside custom Python and C++ scripts.                                        #
#                                                                                                 #
#  Usage:                                                                                         #
#  saveCommand script/BCFtoolsPre.bash                                                            #
#                                                                                                 #
#  Copyleft (ɔ) 2025 by Thiago Andrade Franco                                                     #
#                       <thiago.franco@fundacaobutantan.org.br>                                   #
#                                                                                                 #
#  23/04/2025: First version.                                                                     #
###################################################################################################

# Settng the directories. 
mkdir -p final input job output

for MULTIGENIC in DGF-1 GP63 RHS TS MUC MASP HIST
do
  mkdir -p output/${MULTIGENIC}
done

# Storing initial processing date and time.
date > log/processingStart.date

# Making a symbolic link for input data 
     ln -s ${GENOME_FASTA} input/genome.fasta
     ln -s ${GENOME_GFF} input/genome.gff

# Making a symbolic link to indexed genome and chromosomes sizes.
ln -s /project/carol/dnascent/project/D-NAscent-Origins/metaData/genome-chromoSizes.txt input/
ln -s /project/carol/dnascent/project/D-NAscent-Origins/metaData/genome.fasta.fai input/
ln -s /project/carol/dnascent/project/D-NAscent-Origins/metaData/polycistrons.bed input/polycistrons.bed

# Making the symbolic link to origins from D-NAscent
ln -s /project/carol/dnascent/project/D-NAscent-Origins/03b-frequencyClassification/awk/final/\
nonSynchronized-lessFrequent.bed input/origins.bed
ln -s /project/carol/dnascent/project/D-NAscent-Origins/03b-frequencyClassification/awk/final/\
nonSynchronized-moreFrequent.bed input/miniInitiationZones.bed

# Making the symbolic link to termination from D-NAscent
ln -s /project/carol/dnascent/project/D-NAscent-Origins/03b-frequencyClassification/awk-term/final/\
nonSynchronized-lessFrequent.bed input/terminations.bed
ln -s /project/carol/dnascent/project/D-NAscent-Origins/03b-frequencyClassification/awk-term/final/\
nonSynchronized-moreFrequent.bed input/miniTerminationZones.bed

# Making the symbolic link to VCF files.
ln -s /project/carol/dnascent/project/D-NAscent-Origins/09-SNPs-analisys/\
BCFtools-Nanopore/output/sample1.vcf input/
ln -s /project/carol/dnascent/project/D-NAscent-Origins/09-SNPs-analisys/\
BCFtools-Nanopore/output/sample2.vcf input/
ln -s /project/carol/dnascent/project/D-NAscent-Origins/09-SNPs-analisys/\
BCFtools-Nanopore/output/sample3.vcf input/
ln -s /project/carol/dnascent/project/D-NAscent-Origins/09-SNPs-analisys/\
BCFtools-Nanopore/output/sample4.vcf input/

# Making the symbolic link to VCF files. 
ln -s /project/carol/dnascent/project/D-NAscent-Origins/09-SNPs-analisys/\
BCFtools-Nanopore/output/1_filtered.bam  input/
ln -s /project/carol/dnascent/project/D-NAscent-Origins/09-SNPs-analisys/\
BCFtools-Nanopore/output/2_filtered.bam  input/
ln -s /project/carol/dnascent/project/D-NAscent-Origins/09-SNPs-analisys/\
BCFtools-Nanopore/output/3_filtered.bam  input/
ln -s /project/carol/dnascent/project/D-NAscent-Origins/09-SNPs-analisys/\
BCFtools-Nanopore/output/4_filtered.bam  input/

#  # Making the symbolic link to orc1b and orc1cdc6
ln -s /project/carol/chiporcs/project/01-ChIPSeq/tryCru-clb/tryCru-clb1/leta/orc1cdc6/\
04-significantPeaks/homer/marcela/output/finalPeaks/finalPeaksMultimappersOrc1Cdc6allReplicates.bed  input/Orc1Cdc6.bed
ln -s /project/carol/chiporcs/project/01-ChIPSeq/tryCru-clb/tryCru-clb1/leta/orc1b/\
04-significantPeaks/homer/marcela/output/finalPeaks/finalPeaksUniqueOrc1bAllReplicates.bed input/Orc1B.bed


# Making symbolic link to genome compartments
ln -s  /project/carol/dnascent/project/D-NAscent-Origins/04-Annotation-GenomeCompartment/\
bedtools/output/both-Compartment.gff input/GpDR.gff
ln -s  /project/carol/dnascent/project/D-NAscent-Origins/04-Annotation-GenomeCompartment/\
bedtools/output/core-Compartment.gff input/core.gff
ln -s  /project/carol/dnascent/project/D-NAscent-Origins/04-Annotation-GenomeCompartment/\
bedtools/output/disruptive-Compartment.gff input/disruptive.gff

# Writing the command lines necessary to run this pipeline.
cat > cmdLine.bash << EOI

# Copying the template scripts.
cp -a /project/carol/dnascent/pipeline/dnascentOriginsProcessing/06-SNPsAnalisys/BCFtools/* .

# Running bedtoolsDriver script.
saveCommand script/BCFtoolsDriver.bash\
  2>&1 | tee log/BCFtoolsDriver.out

# Checking result.
saveCommand script/BCFtoolsCheck.bash\
  2>&1 | tee log/BCFtoolsCheck.out

# Removing intermediate files.
saveCommand script/BCFtoolsClean.bash\
  2>&1 | tee log/BCFtoolsClean.out

EOI

exit 0

